# -*- coding: utf-8 -*-
"""Assignment 2 abulhassan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qqEExMcTqzGX2jZcZsN2uZOSsPmDgyoJ
"""

import pandas as pd
path="/D.csv"
df=pd.read_csv(path)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df

sns.relplot(data=df,x="Pulse",y="Calories")

sns.relplot(data=df,x="Pulse",y="Calories",hue='Maxpulse')

sns.relplot(data=df,x="Pulse",y="Calories",hue='Maxpulse',style='Duration')

